Add -E as shortcut for --exclude-pattern
eliben/pss pull request #75
Opened 2023-08-16 12:01 UTC by mpenning

'-E' is a time-saver to avoid '--exclude-pattern' spam if you need to exclude matching on a lot of character patterns

2023-08-16 18:54 UTC, eliben requested changes
Thanks!
Can you add a sanity test to `test_pssmain.py`?

2023-08-17 10:45 UTC, mpenning commented
> Can you add a sanity test to `test_pssmain.py`?

I just did... I expanded one of the existing test methods... please see commit [`d380e2e`](https://github.com/mpenning/pss/commit/d380e2e04b197902ebab61a7355a27e008ad018b)

2023-08-17 13:05 UTC, eliben reviewed
Thanks for adding the test; seems like it's failing -- you may need to reset `self.of` or do a separate test

2023-08-17 13:05 UTC, eliben commented on psslib/pss.py
> +
Please remove this

2023-08-18 04:32 UTC, mpenning commented on psslib/pss.py
> +
Done...

2023-08-18 12:54 UTC, eliben commented
Please fix the failing tests

2025-01-03 13:47 UTC, eliben approved these changes

2025-01-03 13:51 UTC, merged